library(wordcloud)
library(tm)
library(stringr)
library(plotly)
library(ggplot2)
library(ggmap)

geo.point <- readRDS('geo.point.rds')
geo.state <- readRDS('geo.state.rds')
player.tweets <- readRDS('player.tweets.rds')
HoustonRockets <- readRDS('HoustonRockets.rds')
JH <- readRDS('JH.rds')
player.sentiment <- readRDS('player.sentiment.rds')

wordCorpus1 <- Corpus(VectorSource(str_replace_all(HoustonRockets$text, "@", "")))
wordCorpus1 <- tm_map(wordCorpus1, removePunctuation)
wordCorpus1 <- tm_map(wordCorpus1, content_transformer(tolower))
wordCorpus1 <- tm_map(wordCorpus1, removeWords, stopwords("english"))
wordCorpus1 <- tm_map(wordCorpus1, removeWords, c("houston","rockets"))
wordCorpus1 <- tm_map(wordCorpus1, stripWhitespace)

wordCorpus2 <- Corpus(VectorSource(str_replace_all(JH$text, "@", "")))
wordCorpus2 <- tm_map(wordCorpus2, removePunctuation)
wordCorpus2 <- tm_map(wordCorpus2, content_transformer(tolower))
wordCorpus2 <- tm_map(wordCorpus2, removeWords, stopwords("english"))
wordCorpus2 <- tm_map(wordCorpus2, removeWords, c("james","harden"))
wordCorpus2 <- tm_map(wordCorpus2, stripWhitespace)
